### ISSUE TITLE
manchmal heißt "velocity" -> "VELOCITY" haha

### ISSUE THREAD

**Issue by felixkru** [felixkru/Big-Data#13]
z.B. bei file -> "006b0b34-324b-496a-8ed7-a40f7d689ee9"

![grafik](https://github.com/felixkru/Big-Data/assets/140727119/a3fd9798-0d15-47d8-8675-ff88916471d7)

**Comment by lk24dx** [comment]
@felixkru ich raste aus, welcher Typ sitzt bei Rosen und macht sowas. Aber ich fixe es
