### ISSUE TITLE
Leere Datensätze

### ISSUE THREAD

**Issue by felixkru** [felixkru/Big-Data#14]
Hier liste ich einmal auf wieviele Datensätze es im aktuellen stand gibt bei denen kein array vorhanden ist -> also z.B. velocity : ""

velocity -> 15

defect_channel -> 0

wall_thickness -> 13

magnetization -> 0

distance -> 0

timestamp -> 5

**Comment by felixkru** [comment]
files bei denen die velocity so aussieht: 

006b0b34-324b-496a-8ed7-a40f7d689ee9
0c166604-7cd0-4846-b0b6-6c566349589d
4a93c92e-402f-41c4-b0b6-406cb39f32e2
6b260628-e064-41a2-9b78-5f23d405a97a
7d79f876-8d71-42ab-9f85-61b54856df93
8356e54a-b958-4ef7-aebc-88c3fc80a0b4
9bb9bc43-0296-4311-91f8-d2e016cd6afd
a398f580-24ce-4b24-ab32-3a87e9687426
c32fac6e-8411-4f95-815b-28f515ab4386
bf6d122e-d0bc-4a2b-b908-0eaf0ef3a2b9
c5cd5ead-3949-4990-9add-09d07154564f
e3d882f2-0ca5-439f-a19d-2b3aadd4f0e6
e89dd6a2-0917-4eec-8fc4-9f31824d2c42
ff1de9c2-7098-4d51-9e75-1d5990fcec55
fd630121-1f33-4e0b-b3a1-367cf475cec9

**Comment by felixkru** [comment]
files bei denen wall_thickness so aussieht:

110af9fa-e1df-4f6c-abfc-4eca628569a1
1604c120-7e6e-4d25-88f0-8814ee09e249
28cd2906-cda8-49f5-b343-8c6ff2733f44
35a327a5-62f3-47d2-ad9c-59db25710e5d
41ac5bd8-eb70-4fc7-9e19-b8543450dd2c
4e61d255-c89b-4663-931a-541d02dd2da5
5406316d-06fd-433e-bba6-40411af2a85b
572a0ee1-068d-4c84-b1a7-3f11d2715a31
a16c4bb2-ea23-43d2-a341-f9ed76c96aed
a14fc0aa-0b1e-4d30-9fb6-1b1353b37da7
d6b28458-4580-46a1-9d1c-83c7c6a31a3d
e84a72ef-0b79-4de8-9a63-3cdb8307fdb1
ec87a306-c9fe-48c6-839c-125eaca4defb

**Comment by felixkru** [comment]
files bei denen timestamp so aussieht:

0cb83555-f3ea-46e8-9283-433b3d6e7c13
5b212211-0009-4f48-bfd0-3d2065b0d051
6b260628-e064-41a2-9b78-5f23d405a97a
95229d5d-a6f7-4680-a207-8ce7bd960fb7
b5689174-c9be-4c13-8bd4-795c35a3b504

**Comment by lk24dx** [comment]
@Fabiancomida ist Proi 1

**Comment by felixkru** [comment]
Wie gehts vorran @Fabiancomida ??

**Comment by felixkru** [comment]
@Fabiancomida

**Comment by felixkru** [comment]
@Fabiancomida schade
