### ISSUE TITLE
Eastereggs und Unlsebare Daten. 

### ISSUE THREAD

**Issue by lk24dx** [felixkru/Big-Data#17]
wall_thikness: 6, z.B. da475742-4cfa-44ce-aaaf-0292a976a928
magentization: 328, z.B. 713705d9-7545-4e4c-a871-af8e795053e0
defect_channel: 0
distance: 0

**Comment by lk24dx** [comment]
@Fabiancomida , @felixkru das sind Eastereggs, die würde ich letztendlich aus unserem Datensatz komplett rauslösschen

**Comment by lk24dx** [comment]
@Fabiancomida kannst du dir einmal die folgenden Dateien angucken? Bei denen kann keine velocity berechnet werden.
d19dde88-83ba-45e6-b23a-e3f1412ffd55
97e64a10-f0bb-4d8f-a817-eaeec61220e9
93ed6f3a-1052-4904-88cb-45f0b274efda
37b0db44-7031-4126-b675-6757e3f3b9d9
db543678-c8b3-4e0a-a975-4c6bc576a9e5
967ae2ff-8ae2-4ce5-8b59-4284790aea4b
7ba81bc7-8f0a-4297-b68c-f022b0fbea49
1f9d7877-9421-415c-8ac7-613edc4151bd
bae27d5d-f01e-41dc-8417-343021aa235e
17719c05-c3ea-46e4-bfdf-95d2400605c4
2763bdfc-313b-45b4-a894-fe17f9bc5619
5f0d9689-3543-4b10-b9cd-027de5e7fb66
5395c203-2ae8-4b00-b359-8b523be5b9d5
e612eaad-48b4-4773-8104-7f978d40c65b
e2afe6a5-f5f9-46e0-9cd5-66c5a4f8dbd6
6f2eccd8-06bc-4f5a-8490-c11f713289df
d7e1b12b-94f4-4f36-9b22-7d6a366a5a2b
c6b735a5-eab5-4985-a311-40de687418eb
42e4915e-6095-4de8-a437-d51436ac20e1
9eeb96bf-0aaf-441a-aa88-b109892848fb
311a2b49-86af-4e3d-828d-88bb815d9b8c
12c01245-4760-4add-bf87-56b9a5eeb085
6fb04d00-6c02-4444-89d9-29c88ce262c6
8829dab3-69da-4fce-8e79-beb3d6aefbf1
85822dfb-b607-49fd-a894-4503c0f24b21
907badd5-f2f9-4e17-a7d7-1b9bf8e9b239
b942a2d6-7f4b-4070-9073-ef126e5a958a
1991c697-77bb-413e-b72b-335054bb4520
99353c22-76ed-44fa-9cba-32729e8216b9
d92abeac-961b-48fb-9e87-b017121f46d2
5d21ec84-63f9-436e-b34c-8294fb633ec4
f5d8bee6-2dae-4d10-9d17-3015f6654b54
3d4e8f8d-2fae-4a5a-a136-5563a8b22a51
45a691c7-b7de-4ae8-9eb3-241d15832f50
24b307bc-4079-4e6d-b2e3-b83be67391be
f4c2a8b8-461b-4acf-bf3b-258c465fb014
4be44ef9-f3eb-4fbc-be9c-6691083b0e34
a903fb37-d431-423d-aba6-a9d1bf37c1d6
29318570-1cf2-4b2d-97af-b2b01c62eeb8
d796f77f-d344-457c-b4ab-ac261ab315f2

**Comment by Fabiancomida** [comment]
Mittlerweile irrelevant
